Remove junk
Signed-off-by: Jrchintu <Harrypetersun@outlook.com>

diff --git a/AOSP/buildbot b/AOSP/buildbot
--- a/AOSP/buildbot
+++ b/AOSP/buildbot
@@ -34,41 +34,41 @@ export RC1="$rcloneconfig"
 export TZ="Asia/Kolkata"
 export NL=$'\n'
 function TG() {
-    TEXT1="$1"
-    M_ID=$(curl -s "https://api.telegram.org/bot${BOTAPI}/sendmessage" \
-        -d "text=$1&chat_id=${ID}" \
-        -d "disable_web_page_preview=true" \
-        -d "parse_mode=html" | jq .result.message_id) 1>/dev/null
+	TEXT1="$1"
+	M_ID=$(curl -s "https://api.telegram.org/bot${BOTAPI}/sendmessage" \
+		-d "text=$1&chat_id=${ID}" \
+		-d "disable_web_page_preview=true" \
+		-d "parse_mode=html" | jq .result.message_id) 1>/dev/null
 }
 function TGEDIT() {
-    TEXT2="$2"
-    curl -s -X POST https://api.telegram.org/bot"${BOTAPI}"/editMessageText \
-        -d chat_id="$ID" \
-        -d message_id="$1" \
-        -d text="$TEXT2" \
-        -d silent=true | jq . 1>/dev/null
+	TEXT2="$2"
+	curl -s -X POST https://api.telegram.org/bot"${BOTAPI}"/editMessageText \
+		-d chat_id="$ID" \
+		-d message_id="$1" \
+		-d text="$TEXT2" \
+		-d silent=true | jq . 1>/dev/null
 }
 function TGDOC() {
-    curl -F chat_id="${ID}" \
-        -F document=@"$1" \
-        -F caption="$2" https://api.telegram.org/bot"${BOTAPI}"/sendDocument >/dev/null
+	curl -F chat_id="${ID}" \
+		-F document=@"$1" \
+		-F caption="$2" https://api.telegram.org/bot"${BOTAPI}"/sendDocument >/dev/null
 }
 function DEL() {
-    RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
-        echo "DEL-ERROR" >&2
-        return 1
-    }
-    KEY=$(printf "%s\n" "${RESULT}" | cut -d '"' -f6)
-    echo "https://del.dog/${KEY}"
+	RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
+		echo "DEL-ERROR" >&2
+		return 1
+	}
+	KEY=$(printf "%s\n" "${RESULT}" | cut -d '"' -f6)
+	echo "https://del.dog/${KEY}"
 }
 function COM() {
-    tar --use-compress-program="pigz -k -$2 " -cf "$1".tar.gz "$1"
+	tar --use-compress-program="pigz -k -$2 " -cf "$1".tar.gz "$1"
 }
 function T1() {
-    date +"%I:%M%p"
+	date +"%I:%M%p"
 }
 function TRIM() {
-    grep -iE 'crash|avc|error|fail|fatal|failed|missing' "$1" &>"Trim-$1"
+	grep -iE 'crash|avc|error|fail|fatal|failed|missing' "$1" &>"Trim-$1"
 }
 
 # Rclone Config
@@ -92,29 +92,29 @@ git clone --depth=1 "$local_manifest" -b corvus .repo/local_manifests
 
 # Final Sync
 repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 ||
-    repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j "$(nproc -all)"
+	repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j "$(nproc -all)"
 
 ###########################################
 ######### DOWNLOAD & SETUP CCACHE #########
 ###########################################
 # Ccache
 if [[ "$USE_CCACHE" = "1" ]]; then
-    #Download ccache
-    cd "$CCACHE_DIR" || exit
-    rm -rf .ccache ccache
-    time aria2c "$CCACHEURL" -x16 -s50
-    time tar xf ccache.tar.gz
-    rm -rf ccache.tar.gz
+	#Download ccache
+	cd "$CCACHE_DIR" || exit
+	rm -rf .ccache ccache
+	time aria2c "$CCACHEURL" -x16 -s50
+	time tar xf ccache.tar.gz
+	rm -rf ccache.tar.gz
 
-    #Set ccache
-    export CCACHE_DIR="$CCACHEDIR"
-    export CCACHE_EXEC="$(which ccache)"
-    ccache -M "$CCACHESIZE"
-    ccache -o compression=true
+	#Set ccache
+	export CCACHE_DIR="$CCACHEDIR"
+	export CCACHE_EXEC="$(which ccache)"
+	ccache -M "$CCACHESIZE"
+	ccache -o compression=true
 
-    #ccache notification
-    TG "$(ccache -s)"
-    export B2="$M_ID"
+	#ccache notification
+	TG "$(ccache -s)"
+	export B2="$M_ID"
 fi
 
 ############################################
@@ -137,12 +137,12 @@ TGEDIT "$INFO" "$TEXT1""$NL""$(T1):Env Setup And Lunch"
 
 # Make Metalava Seperately
 if [[ "$METALAVA" = "true" ]]; then
-    TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Metalava Build Started"
-    export WITHOUT_CHECK_API=true
-    make api-stubs-docs || echo SKIPPING
-    make system-api-stubs-docs || echo SKIPPING
-    make test-api-stubs-docs || echo SKIPPING
-    TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Metalava Build Done"
+	TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Metalava Build Started"
+	export WITHOUT_CHECK_API=true
+	make api-stubs-docs || echo SKIPPING
+	make system-api-stubs-docs || echo SKIPPING
+	make test-api-stubs-docs || echo SKIPPING
+	TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Metalava Build Done"
 fi
 
 # Main Build Step
@@ -154,36 +154,36 @@ TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Main Build upto $END"
 
 # Build %'age and kill in 85m if build type is ccache
 if [[ "$BUILD_TYPE" = "ccache" ]]; then
-    while test ! -z "$(pidof soong_ui)"; do
-        if [[ "$(date +"%I:%M%p")" = "$END" ]]; then
-            kill %1
-            TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Killed FOR CCACHE UPLOAD"
-            break
-        else
-            sleep 120
-            BUILD_STATS=$(tail <"ErrorLog.txt" -n 1 | awk '{ print $2 }')
-            TGEDIT "$B3" "$(T1)=$BUILD_STATS" && TGEDIT "$B2" "$(ccache -s)"
-        fi
-    done
+	while test ! -z "$(pidof soong_ui)"; do
+		if [[ "$(date +"%I:%M%p")" = "$END" ]]; then
+			kill %1
+			TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Killed FOR CCACHE UPLOAD"
+			break
+		else
+			sleep 120
+			BUILD_STATS=$(tail <"ErrorLog.txt" -n 1 | awk '{ print $2 }')
+			TGEDIT "$B3" "$(T1)=$BUILD_STATS" && TGEDIT "$B2" "$(ccache -s)"
+		fi
+	done
 else
-    while test ! -z "$(pidof soong_ui)"; do
-        sleep 120
-        BUILD_STATS=$(tail <"ErrorLog.txt" -n 1 | awk '{ print $2 }')
-        TGEDIT "$B3" "$(T1)=$BUILD_STATS" && TGEDIT "$B2" "$(ccache -s)"
-    done
+	while test ! -z "$(pidof soong_ui)"; do
+		sleep 120
+		BUILD_STATS=$(tail <"ErrorLog.txt" -n 1 | awk '{ print $2 }')
+		TGEDIT "$B3" "$(T1)=$BUILD_STATS" && TGEDIT "$B2" "$(ccache -s)"
+	done
 fi
 
 ###########################################
 ########## Send Logs If Failed ############
 ###########################################
 for B4 in *txt; do
-    if [ -e "$B4" ]; then
-        TRIM "$B4"
-        TGDOC "$B4" "$(DEL "$B4")"
-        TGDOC "Trim-$B4" "$(DEL Trim-"$B4")"
-    else
-        break
-    fi
+	if [ -e "$B4" ]; then
+		TRIM "$B4"
+		TGDOC "$B4" "$(DEL "$B4")"
+		TGDOC "Trim-$B4" "$(DEL Trim-"$B4")"
+	else
+		break
+	fi
 done
 TGDOC "./out/*log" "$(DEL ./out/*log)" || exit
 
@@ -191,35 +191,35 @@ TGDOC "./out/*log" "$(DEL ./out/*log)" || exit
 ######## Upload Rom If Zip Found ##########
 ###########################################
 if ls /tmp/rom/out/target/product/mido/*zip* 1>/dev/null 2>&1; then
-    for LOOP in /tmp/rom/out/target/product/mido/*zip*; do
-        mkdir -p out/target/product/mido/old
-        if [ -e "$LOOP" ]; then
-            rclone copy "$LOOP" GDUP:ROM/ZIP
-            mv "$LOOP" out/target/product/mido/old
-            TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Rom Uploaded"
-            TG "ROM URL:-https://rom.jrchintu.ga/0:/ZIP/$LOOP"
-        else
-            break
-        fi
-    done
+	for LOOP in /tmp/rom/out/target/product/mido/*zip*; do
+		mkdir -p out/target/product/mido/old
+		if [ -e "$LOOP" ]; then
+			rclone copy "$LOOP" GDUP:ROM/ZIP
+			mv "$LOOP" out/target/product/mido/old
+			TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Rom Uploaded"
+			TG "ROM URL:-https://rom.jrchintu.ga/0:/ZIP/$LOOP"
+		else
+			break
+		fi
+	done
 else
-    tmate -S /tmp/tmate.sock new-session -d &&
-        tmate -S /tmp/tmate.sock wait tmate-ready &&
-        SENDSHELL=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}') &&
-        TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Build Failed OR Zip Not Found" &&
-        TG "$SENDSHELL"
+	tmate -S /tmp/tmate.sock new-session -d &&
+		tmate -S /tmp/tmate.sock wait tmate-ready &&
+		SENDSHELL=$(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}') &&
+		TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Build Failed OR Zip Not Found" &&
+		TG "$SENDSHELL"
 fi
 
 ###########################################
 ############## Upload ccache ##############
 ###########################################
 if [[ "$BUILD_TYPE" = "ccache" ]]; then
-    cd /tmp || exit
-    TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Uploading ccache"
-    COM ccache 1
-    rclone copy ccache.tar.gz GDUP:ROM/CCACHE
-    TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Ccache Uploaded"
-    cd /tmp/rom || exit
+	cd /tmp || exit
+	TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Uploading ccache"
+	COM ccache 1
+	rclone copy ccache.tar.gz GDUP:ROM/CCACHE
+	TGEDIT "$INFO" "$TEXT2""$NL""$(T1):Ccache Uploaded"
+	cd /tmp/rom || exit
 fi
 
 ###########################################
